# Generated by Django 3.2 on 2022-07-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(unique=True, verbose_name='作業日')),
                ('is_finished', models.BooleanField(default=False, verbose_name='終了したかどうか')),
                ('average_plan_excution_time_rate', models.FloatField(blank=True, default=0, verbose_name='平均計画実行時間割合')),
                ('todo_achievement_rate_in_a_day', models.FloatField(blank=True, default=0, verbose_name='1日の進捗率')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='スラッグ')),
                ('create_at', models.DateTimeField(verbose_name='登録日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '作業モデル',
                'verbose_name_plural': '作業リスト',
            },
        ),
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ToDo')),
                ('limit_time', models.DateTimeField(verbose_name='期限')),
                ('expected_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='目標時間（秒）')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='作業順')),
                ('actual_time', models.PositiveSmallIntegerField(default=0, verbose_name='実際の時間（秒）')),
                ('plan_excution_time_rate', models.FloatField(blank=True, default=0, verbose_name='計画実行時間割合')),
                ('achievement_rate', models.IntegerField(default=0, verbose_name='ToDo達成割合（%）')),
                ('create_at', models.DateTimeField(verbose_name='登録日時')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
                ('work_date_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todomodel_list', to='todolist.workdatemodel', verbose_name='作業日')),
            ],
            options={
                'verbose_name': 'ToDoモデル',
                'verbose_name_plural': 'ToDoリスト',
            },
        ),
    ]
