# Generated by Django 3.2 on 2022-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdatemodel',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='スラッグ'),
        ),
        migrations.AddConstraint(
            model_name='workdatemodel',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='unique_slug_in_user'),
        ),
    ]
